console.log("=".repeat(55));
console.log("JAVASCRIPT PROGRAMMING LABORATORY - VERIFIED EXECUTION");
console.log("STUDENT: [Yamikani Chanza]");
console.log("ID: [24313351002]");
console.log("PROGRAM: [program-45] - [Methods that modify arrays]");
console.log("EXECUTION DATE: " + new Date().toLocaleString());
console.log("SESSION TOKEN: " + Math.random().toString(36).substring(2, 15).toUpperCase());
console.log("VERIFICATION HASH: " + btoa("[24313351002]" + Date.now()).substring(0, 12));
console.log("=".repeat(55));

// Program 45: Methods that modify arrays
let fruits = ['apple', 'banana', 'orange'];
console.log("Original array:", fruits);
console.log("\n--- push() - add to end ---");
let pushResult = fruits.push('mango', 'grape');
console.log("After push:", fruits);
console.log("push() return value (new length):", pushResult);
console.log("\n--- pop() - remove from end ---");
let popped = fruits.pop();
console.log("After pop():", fruits);
console.log("pop() return value:", popped);
console.log("\n--- unshift() - add to beginning ---");
let unshiftResult = fruits.unshift('kiwi', 'peach');
console.log("After unshift():", fruits);
console.log("unshift() return value:", unshiftResult);
console.log("\n--- shift() - remove from beginning ---");
let shifted = fruits.shift();
console.log("After shift():", fruits);
console.log("shift() return value:", shifted);
console.log("\n--- splice() - Swiss Army knife ---");
let colors = ['red', 'green', 'blue', 'yellow', 'purple'];
console.log("Colors array:", colors);
// Remove elements
let removed = colors.splice(1, 2);
console.log("\nAfter splice(1, 2) - remove 2 from index 1:");
console.log("Modified array:", colors);
console.log("Removed elements:", removed);
// Insert elements
colors = ['red', 'green', 'blue'];
console.log("\nBefore insert:", colors);
colors.splice(1, 0, 'yellow', 'orange');
console.log("After splice(1, 0, 'yellow', 'orange'):", colors);
// Replace elements
colors = ['red', 'green', 'blue'];
console.log("\nBefore replace:", colors);
let replaced = colors.splice(1, 1, 'cyan', 'magenta');
console.log("After splice(1, 1, 'cyan', 'magenta'):", colors);
console.log("Replaced element:", replaced);
console.log("\n--- splice() with negative index ---");
let letters = ['a', 'b', 'c', 'd', 'e'];
console.log("Letters:", letters);
let removedFromEnd = letters.splice(-2, 1);
console.log("After splice(-2, 1):", letters);
console.log("Removed:", removedFromEnd);
console.log("\n--- fill() - fill array with value ---");
let numbers = [1, 2, 3, 4, 5];
console.log("Original:", numbers);
numbers.fill(0);
console.log("After fill(0):", numbers);
numbers = [1, 2, 3, 4, 5];
numbers.fill(9, 1, 4);
console.log("After fill(9, 1, 4):", numbers);
console.log("\n--- copyWithin() - copy within array ---");
let arr = [1, 2, 3, 4, 5];
console.log("Original:", arr);
arr.copyWithin(0, 3);
console.log("After copyWithin(0, 3):", arr);
arr = [1, 2, 3, 4, 5];
arr.copyWithin(1, 2, 4);
console.log("After copyWithin(1, 2, 4):", arr);
console.log("\n--- Practical Stack and Queue Examples ---");
// Stack (LIFO) using push/pop
let stack = [];
stack.push('page1');
stack.push('page2');
stack.push('page3');
console.log("Stack:", stack);
console.log("Pop:", stack.pop());
console.log("Pop:", stack.pop());
console.log("Stack after pops:", stack);
// Queue (FIFO) using push/shift
let queue = [];
queue.push('task1');
queue.push('task2');
queue.push('task3');
console.log("\nQueue:", queue);
console.log("Dequeue:", queue.shift());
console.log("Dequeue:", queue.shift());
console.log("Queue after dequeues:", queue);